#!/usr/bin/env python
"""Write the canonical shared name pool into every generator that consumes it.

The same 1000-name pool was hand-copied into three generators, which is fine until
someone edits one of them. This makes shared/name-pool.json the single copy and pushes
it outward; --check fails if any consumer has drifted, which is the mode worth wiring
into anything automated.

  py tools/sync-name-pool.py            write the pool into every consumer
  py tools/sync-name-pool.py --check    report drift and exit 1 if any; writes nothing

NOT consumers, by Xero's ruling of 2026-09-11: mothership-generator and
space1999generator keep bespoke pools. Mothership's is split given/family and this pool
is single given names only, so adopting it would LOSE structure rather than gain names.
Do not add them here.

The two src/-based generators need `py src/assemble.py` afterwards to rebuild their
index.html; this script does not assemble, and says so when it changes one.
"""
import argparse
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CANON = os.path.join(REPO, "shared", "name-pool.json")
# TheTable and the generators are siblings two levels up, for both the main checkout
# and every lane worktree.
DEFAULT_GENS = os.path.normpath(os.path.join(REPO, "..", "..", "RPG Character Generators"))

# walkingdead-rpg is hand-built with no src/, so its pool is an inline array in the page.
# The first sync wraps it in markers; every sync after that is an exact block replacement
# rather than a regex rewrite of live code. Same approach as apegenerator's embed-sheet.py.
WD_START = "/* name-pool:start -- generated by TheTable tools/sync-name-pool.py, do not edit by hand */"
WD_END = "/* name-pool:end */"


def sha(names):
    return hashlib.sha1(json.dumps(names).encode("utf-8")).hexdigest()[:12]


def read_canonical():
    d = json.load(io.open(CANON, encoding="utf-8"))
    names = d["names"]
    if len(names) != len(set(names)):
        dupes = sorted({n for n in names if names.count(n) > 1})
        raise SystemExit("canonical pool has duplicate entries: %s" % dupes[:8])
    if d.get("_count") not in (None, len(names)):
        raise SystemExit("canonical _count %s disagrees with %d names" % (d.get("_count"), len(names)))
    return names


def detect_indent(text, default=1):
    """Whatever indent the file already uses. Rewriting a 1000-entry file in a different
    indent turns a one-name change into a thousand-line diff, which makes the change
    unreviewable -- the tool should touch only what it must."""
    m = re.search(r'^\{\r?\n( +)"', text)
    return len(m.group(1)) if m else default


def sync_json_pool(path, names, check):
    """traveller and 2300ad: {_source, _count, names} -- replace names and _count only."""
    if not os.path.exists(path):
        return ("missing", None)
    raw = io.open(path, encoding="utf-8").read()
    d = json.loads(raw)
    if d.get("names") == names and d.get("_count") == len(names):
        return ("ok", sha(d["names"]))
    if check:
        return ("DRIFTED", sha(d.get("names") or []))
    d["names"] = names
    d["_count"] = len(names)
    # match the file's own indent AND its trailing-newline convention: a sync tool that
    # reformats is a sync tool whose diffs nobody reads
    out = json.dumps(d, indent=detect_indent(raw), ensure_ascii=False)
    if raw.endswith("\n"):
        out += "\n"
    io.open(path, "w", encoding="utf-8", newline="\n").write(out)
    return ("written", sha(names))


def sync_inline_pool(path, names, check):
    """walkingdead: an inline `var NAME_POOL = [...]`, marked on first sync."""
    if not os.path.exists(path):
        return ("missing", None)
    s = io.open(path, encoding="utf-8").read()
    # compact separators to match how the array was already written, so the one-time
    # marker insertion is the only real change on that line
    block = "var NAME_POOL = %s;" % json.dumps(names, ensure_ascii=False, separators=(",", ":"))

    marked = re.search(re.escape(WD_START) + r".*?" + re.escape(WD_END), s, re.S)
    if marked:
        current = re.search(r"var NAME_POOL\s*=\s*(\[.*?\]);", marked.group(0), re.S)
        have = json.loads(current.group(1)) if current else None
        if have == names:
            return ("ok", sha(have))
        if check:
            return ("DRIFTED", sha(have or []))
        s = s[:marked.start()] + WD_START + "\n" + block + "\n" + WD_END + s[marked.end():]
    else:
        raw = re.search(r"var NAME_POOL\s*=\s*(\[.*?\]);", s, re.S)
        if not raw:
            return ("no pool found", None)
        have = json.loads(raw.group(1))
        if check:
            # unmarked is itself a finding: the next sync would have to regex live code
            return ("ok, UNMARKED" if have == names else "DRIFTED, UNMARKED", sha(have))
        s = s[:raw.start()] + WD_START + "\n" + block + "\n" + WD_END + s[raw.end():]
    io.open(path, "w", encoding="utf-8", newline="\n").write(s)
    return ("written", sha(names))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 if any consumer disagrees; writes nothing")
    ap.add_argument("--generators", default=DEFAULT_GENS,
                    help="path to the generator repos (default: %(default)s)")
    args = ap.parse_args()

    names = read_canonical()
    print("canonical %s -- %d names, sha1 %s" % (os.path.relpath(CANON, REPO), len(names), sha(names)))
    if not os.path.isdir(args.generators):
        raise SystemExit("generator directory not found: %s" % args.generators)

    targets = [
        ("traveller-generator", os.path.join(args.generators, "traveller-generator", "src", "data", "names.json"), sync_json_pool, True),
        ("2300ad-generator", os.path.join(args.generators, "2300ad-generator", "src", "data", "names.json"), sync_json_pool, True),
        ("walkingdead-rpg", os.path.join(args.generators, "walkingdead-rpg", "index.html"), sync_inline_pool, False),
    ]

    drift, wrote, needs_assemble = [], [], []
    for name, path, fn, is_src in targets:
        status, got = fn(path, names, args.check)
        print("  %-22s %-18s %s" % (name, status, got or ""))
        if "DRIFTED" in status or status in ("missing", "no pool found"):
            drift.append(name)
        if status == "written":
            wrote.append(name)
            if is_src:
                needs_assemble.append(name)

    if args.check:
        if drift:
            print("\nDRIFT: %s" % ", ".join(drift))
            return 1
        print("\nevery consumer matches the canonical pool")
        return 0

    if needs_assemble:
        print("\nnow run `py src/assemble.py` in: %s" % ", ".join(needs_assemble))
        print("(this script writes src/data only -- it does not rebuild index.html)")
    elif not wrote:
        print("\nnothing to do; every consumer already matched")
    return 0


if __name__ == "__main__":
    sys.exit(main())
